name: Deploy to Azure App Service
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: satyr
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
